### ISSUE TITLE
Metadata Getting erased

### ISSUE THREAD

**Issue by harishhari131506** [advanced-cropper/react-advanced-cropper#41] opened 2023-09-25 09:00 UTC
Hi all ! i am creating a image editor for my school project . i have created all components and successfully implemented editor but when i upload a image after doing some operations when i download that image the metadata is getting erased . but i doesn't want it to disappear . is there anyway to retain metadata ?

**Comment by Norserium** [comment] 2023-09-29 21:20
@harishhari131506, that is by design, cause you actually get not an image, you get the canvas content. Though you can retrieve the meta from the original image and pass it along with the cropped result ([example](https://codesandbox.io/s/react-advanced-cropper-meta-6ssmnz?file=/src/index.tsx)).

**Comment by Norserium** [comment] 2024-01-21 10:00
@harishhari131506, I close this issue, but feel free to reopen in the future.

**Closed by Norserium** 2024-01-21 10:00 UTC
